
gmod_ifp.options.label=Настройки Immersive First Person
gmod_ifp.options.toggle=Включить IFP
gmod_ifp.options.crosshair=Включить прицел
gmod_ifp.options.crosshair_color=Цвет прицела
gmod_ifp.options.fov_multiplier=Множитель FOV
gmod_ifp.options.lock_enable=Включить блокировку угла обзора
gmod_ifp.options.lock_enable_help=Блокирует угол обзора в транспорте и снаружи
gmod_ifp.options.lock_vertical=Блокировка угла обзора по вертикали
gmod_ifp.options.lock_vertical_help=Блокирует угол обзора по вертикали вне транспорта (в градусах)
gmod_ifp.options.force_show_head=Принудительно показывать голову
gmod_ifp.options.force_show_head_help=Включает отображение головы. Может мешать обзору
gmod_ifp.options.mod_title=Модификатор
gmod_ifp.options.mod_disabled=Выключено

gmod_ifp.options.weapons_view.label=Настройки вида оружия
gmod_ifp.options.weapons_view.hint=Добавьте конкретное оружие в список с помощью "Редактора вида оружия", чтобы настройки ниже работали
gmod_ifp.options.weapons_view.switch_aim_key=Клавиша для смены типа прицеливания с оружия
gmod_ifp.options.weapons_view.switch_aim_key_help=Эта клавиша меняет только тип прицеливания, само прицеливание происходит, когда вы нажимаете правую кнопку мыши
gmod_ifp.options.weapons_view.disable_when_aim=Выключать IFP, когда вы прицеливаетесь
gmod_ifp.options.weapons_view.disable_when_aim_help=Работает только для оружия из списка, когда вы нажимаете правую кнопку мыши
gmod_ifp.options.weapons_view.open_editor=Открыть редактор вида оружия (список оружия)

gmod_ifp.options.reset_title=Сброс
gmod_ifp.options.reset_button=Сбросить настройки IFP
gmod_ifp.options.reset_button_table=Очистить список/данные вида оружия

gmod_ifp.ui.shader_warn.title=Предупреждение: Immersive First Person
gmod_ifp.ui.shader_warn.text=Для модификатора BodyCam требуется аддон "Simple Custom Shaders" для правильного эффекта BodyCam\n\nВы можете установить по ссылке ниже:
gmod_ifp.ui.shader_warn.link=Открыть страницу "Simple Custom Shaders" в Steam Workshop
gmod_ifp.ui.shader_warn.donotshow=Не показывать снова

gmod_ifp.ui.weapons_editor.title=IFP: Редактор вида оружия
gmod_ifp.ui.weapons_editor.hint=<– Выберите оружие для редактирования вида при\nприцеливании\n\nНажмите ПКМ для быстрого добавления оружия в список
gmod_ifp.ui.weapons_editor.edit_panel.title=Настройки: %s
gmod_ifp.ui.weapons_editor.edit_panel.remove=Удалить оружие из списка
gmod_ifp.ui.weapons_editor.edit_panel.add=Добавить и сохранить оружие

gmod_ifp.warning.lrp_view_conflict=Предупреждение: Аддон "LocalRP - View" конфликтует с аддоном "Immersive First Person". Пожалуйста, отключите или удалите "LocalRP - View".