
gmod_ifp.options.label=Настройки Immersive First Person
gmod_ifp.options.toggle=Вид от первого лица
gmod_ifp.options.lock_toggle=Блокировка вида
gmod_ifp.options.lock_max=Максимальная блокировка (смотря вниз)
gmod_ifp.options.crosshair=Прицел
gmod_ifp.options.crosshair_color=Цвет прицела
gmod_ifp.options.mod_title=Модификатор
gmod_ifp.options.mod_disabled=Выключено

gmod_ifp.ui.shader_warn.title=Предупреждение: Immersive First Person
gmod_ifp.ui.shader_warn.text=Для эффекта BodyCam требуется аддон "Simple Custom Shaders"\n\nВы можете установить по ссылке ниже:
gmod_ifp.ui.shader_warn.link=Открыть страницу "Simple Custom Shaders" в Steam Workshop