
gmod_ifp.options.label=Immersive First Person options
gmod_ifp.options.toggle=View toggle
gmod_ifp.options.lock_toggle=View lock
gmod_ifp.options.lock_max=Max lock (looking down)
gmod_ifp.options.crosshair=Crosshair
gmod_ifp.options.crosshair_color=Crosshair color
gmod_ifp.options.mod_title=Modifier
gmod_ifp.options.mod_disabled=Disabled

gmod_ifp.ui.shader_warn.title=Warning: Immersive First Person
gmod_ifp.ui.shader_warn.text=BodyCam shader requires "Simple Custom Shaders" addon\n\nYou can install it at the link below:
gmod_ifp.ui.shader_warn.link=Open "Simple Custom Shaders" page on the Steam Workshop