
gmod_ifp.options.label=Immersive First Person settings
gmod_ifp.options.toggle=Enable IFP
gmod_ifp.options.crosshair=Enable Crosshair
gmod_ifp.options.crosshair_color=Crosshair color
gmod_ifp.options.fov_multiplier=FOV Multiplier
gmod_ifp.options.lock_enable=Enable view angle block
gmod_ifp.options.lock_enable_help=Blocking view angle in vehicle and outside vehicle
gmod_ifp.options.lock_vertical=Vertical view angle block
gmod_ifp.options.lock_vertical_help=Blocking vertical view angle outside vehicle (in degrees)
gmod_ifp.options.mod_title=Modifier
gmod_ifp.options.mod_disabled=Disabled

gmod_ifp.options.weapons_view.label=Weapons view settings
gmod_ifp.options.weapons_view.hint=Add a specific weapon to the list using the "Weapons view editor" for the settings below to work
gmod_ifp.options.weapons_view.switch_aim_key=Key for switch weapon aiming type
gmod_ifp.options.weapons_view.switch_aim_key_help=This key just changes weapon aiming type, aiming is happening when you press right mouse button
gmod_ifp.options.weapons_view.disable_when_aim=Disable IFP when aiming
gmod_ifp.options.weapons_view.disable_when_aim_help=Only for weapons from list when right mouse button is pressed
gmod_ifp.options.weapons_view.open_editor=Open weapons view editor (weapons list)

gmod_ifp.options.reset_title=Reset
gmod_ifp.options.reset_button=Reset IFP settings
gmod_ifp.options.reset_button_table=Clear weapons view list/data

gmod_ifp.ui.shader_warn.title=Warning: Immersive First Person
gmod_ifp.ui.shader_warn.text=BodyCam modifier requires "Simple Custom Shaders" addon for correct BodyCam effect\n\nYou can install it at the link below:
gmod_ifp.ui.shader_warn.link=Open "Simple Custom Shaders" page on the Steam Workshop
gmod_ifp.ui.shader_warn.donotshow=Do not show again

gmod_ifp.ui.weapons_editor.title=IFP: Weapons View Editor
gmod_ifp.ui.weapons_editor.hint=<– Select a weapon to edit view when aiming\n\nRight-click to quickly add weapon to the list
gmod_ifp.ui.weapons_editor.edit_panel.title=Settings: %s
gmod_ifp.ui.weapons_editor.edit_panel.remove=Remove weapon from list
gmod_ifp.ui.weapons_editor.edit_panel.add=Add and save weapon

gmod_ifp.warning.lrp_view_conflict=Warning: "LocalRP - View" addon conflicts with "Immersive First Person" addon. Please, disable or uninstall "LocalRP - View".